# -*- coding: utf-8 -*-
"""One_Sample_Binomial_Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lI7a7WDMxaWRkKIXyy1TWQMBqSEN0XSb
"""

import pandas

student_data = pandas.read_csv('StudentStatistics.csv', sep = ';')
student_data

student_data['Gen_Gender']

student_data['Gen_Gender'].value_counts()

# Hypothesis test

'''
Research Question - Is the number of males and females equal in organisation?

Sample - 46
Male - 34
Female - 12

Null Hypothesis (H0) - There is no difference in the number of male and female in the organisation
Alternative Hypothesis (Ha) - There is a difference in the number of male and female in the organisation

Two-sided test - non directional (equal or unequal)
One-sided test - greater or lesser (directional)
'''

from scipy.stats import binom_test

binom_test(x = 34, n =  46, p = 0.5)
#x - count of a category
#n - sample size
#p - probability to belong to any category

p_value = 0.0016414913408482334

if p_value < 0.05:
    print('Reject the null hypothesis')
else:
    print('Fail to reject the null hypothesis')

# Null Hypothesis is rejected

# There is a difference in the number of male and female in the organisation.